apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-test
  labels:
    app: env-test
  annotations:
    cluster-id: "{{ .Vars.CLUSTER_ID }}"  # Enclose the variable in quotes
    environment: "{{ .Vars.ENVIRONMENT }}"  # Enclose the variable in quotes
    region: "{{ .Vars.REGION }}"  # Enclose the variable in quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-test
  template:
    metadata:
      labels:
        app: env-test
      annotations:
        environment: "{{ .Vars.ENVIRONMENT }}"  # Enclose the variable in quotes
        region: "{{ .Vars.REGION }}"  # Enclose the variable in quotes
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "env && sleep 3600"]
        env:
        - name: CLUSTER_ID
          value: "{{ .Vars.CLUSTER_ID }}"  # Enclose the variable in quotes
        - name: ENVIRONMENT
          value: "{{ .Vars.ENVIRONMENT }}"  # Enclose the variable in quotes
        - name: REGION
          value: "{{ .Vars.REGION }}"  # Enclose the variable in quotes
