apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-test
  labels:
    app: env-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: env-test
  template:
    metadata:
      labels:
        app: env-test
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "echo Printing environment variables && env && sleep 3600"]
        env:
        - name: CLUSTER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['helm.sh/resource-policy']
        - name: ENVIRONMENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['helm.sh/resource-policy']
        - name: REGION
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['helm.sh/resource-policy']
